# Generated by Django 4.2.24 on 2026-01-31 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50, unique=True)),
                ('test_type', models.CharField(choices=[('Unit', 'Unit Test'), ('Integration', 'Integration Test'), ('System', 'System Test')], default='Unit', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('input_data', models.TextField(blank=True, null=True)),
                ('expected_result', models.CharField(max_length=255)),
                ('mapping_method', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('PASS', 'Thành công'), ('FAIL', 'Thất bại'), ('ERROR', 'Lỗi hệ thống')], default='PENDING', max_length=10)),
                ('actual_result', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_dashboard.testcasedefinition')),
            ],
        ),
    ]
